apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  hosts:
    - *
  gateways:
    - istio-system/ingressgateway
  http:
    - name: alertmanager
      match:
        - uri:
            prefix: "/alertmanager"
      route:
      - destination:
          host: monitoring-kube-prometheus-alertmanager
          port:
            number: 9093
