stages:
 - deploy

deploy-istio:
  stage: deploy
  variables:
    KUBE_CONTEXT: devops8121703/k8s-connection:k8s-connection
  image:
    name: istio/istioctl:1.22.0
    entrypoint: [""]
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - istioctl install --set profile=default -y

.deploy-prometheus:
  variables:
    KUBE_CONTEXT: devops8121703/k8s-connection:k8s-connection
  stage: deploy
  image: 
    name: dtzar/helm-kubectl
    entrypoint: [""]
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - helm upgrade --install  monitoring prometheus-community/kube-prometheus-stack --debug -n monitoring --create-namespace --version 58.0.0 --timeout 5m
  when: always