stages:
 - deploy

deploy-prometheus:
  variables:
    KUBE_CONTEXT: devops8121703/k8s-connection:k8s-connection
  stage: deploy
  image: 
    name: registry.gitlab.com/gitlab-org/cluster-integration/helm-install-image:3.16.2-kube-1.30.5-alpine-3.20
    entrypoint: [""]
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    - helm repo update
    - helm upgrade --install  monitoring prometheus-community/kube-prometheus-stack --debug -n monitoring --create-namespace --version 58.0.0 --timeout 5m
  when: always